-- 0002_inventory_procurement.sql
-- Units, inventory, stock ledger, suppliers, receiving, purchasing and supplier credit.

create table if not exists public.units_of_measure (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  dimension text not null
    check (dimension in ('MASS','VOLUME','COUNT','OTHER')),
  factor_to_dimension_base numeric(18,6) not null default 1
    check (factor_to_dimension_base > 0),
  is_active boolean not null default true
);

create table if not exists public.inventory_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  is_active boolean not null default true
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  sku text unique,
  name text not null,
  category_id uuid references public.inventory_categories(id),
  base_uom_id uuid not null references public.units_of_measure(id),
  track_inventory boolean not null default true,
  track_expiry boolean not null default false,
  allow_negative_stock boolean not null default false,
  reorder_level numeric(14,4) not null default 0 check (reorder_level >= 0),
  reorder_target numeric(14,4) check (reorder_target is null or reorder_target >= 0),
  default_shelf_life_days integer check (default_shelf_life_days is null or default_shelf_life_days >= 0),
  notes text,
  is_active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_inventory_items_category on public.inventory_items(category_id);
create index if not exists idx_inventory_items_active on public.inventory_items(is_active);

create trigger trg_inventory_items_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  supplier_code text unique,
  name text not null,
  contact_person text,
  phone text,
  email text,
  address text,
  tin text,
  payment_terms_days integer not null default 0 check (payment_terms_days >= 0),
  notes text,
  is_active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_suppliers_active on public.suppliers(is_active);

create trigger trg_suppliers_updated_at
before update on public.suppliers
for each row execute function public.set_updated_at();

create table if not exists public.supplier_items (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.suppliers(id),
  inventory_item_id uuid not null references public.inventory_items(id),
  supplier_sku text,
  purchase_uom_id uuid not null references public.units_of_measure(id),
  base_quantity_per_purchase_unit numeric(14,4) not null check (base_quantity_per_purchase_unit > 0),
  last_unit_cost numeric(14,4) check (last_unit_cost is null or last_unit_cost >= 0),
  is_preferred boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (supplier_id, inventory_item_id, purchase_uom_id)
);

create index if not exists idx_supplier_items_item on public.supplier_items(inventory_item_id);

create trigger trg_supplier_items_updated_at
before update on public.supplier_items
for each row execute function public.set_updated_at();

create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  purchase_order_number bigint generated by default as identity unique,
  supplier_id uuid not null references public.suppliers(id),
  status text not null default 'DRAFT'
    check (status in ('DRAFT','APPROVED','SENT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
  ordered_at timestamptz,
  expected_date date,
  subtotal numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0 check (discount_amount >= 0),
  tax_amount numeric(14,2) not null default 0 check (tax_amount >= 0),
  shipping_amount numeric(14,2) not null default 0 check (shipping_amount >= 0),
  total_amount numeric(14,2) not null default 0,
  notes text,
  created_by uuid not null references public.profiles(id),
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_purchase_orders_supplier on public.purchase_orders(supplier_id, created_at desc);
create index if not exists idx_purchase_orders_status on public.purchase_orders(status);

create trigger trg_purchase_orders_updated_at
before update on public.purchase_orders
for each row execute function public.set_updated_at();

create table if not exists public.purchase_order_items (
  id uuid primary key default gen_random_uuid(),
  purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id),
  supplier_item_id uuid references public.supplier_items(id),
  purchase_uom_id uuid not null references public.units_of_measure(id),
  ordered_quantity numeric(14,4) not null check (ordered_quantity > 0),
  base_quantity_per_purchase_unit numeric(14,4) not null check (base_quantity_per_purchase_unit > 0),
  unit_cost numeric(14,4) not null check (unit_cost >= 0),
  line_total numeric(14,2) not null check (line_total >= 0),
  notes text
);

create index if not exists idx_po_items_po on public.purchase_order_items(purchase_order_id);

create table if not exists public.goods_receipts (
  id uuid primary key default gen_random_uuid(),
  receipt_number bigint generated by default as identity unique,
  supplier_id uuid not null references public.suppliers(id),
  purchase_order_id uuid references public.purchase_orders(id),
  supplier_invoice_number text,
  supplier_invoice_date date,
  received_at timestamptz not null default now(),
  received_by uuid not null references public.profiles(id),
  status text not null default 'DRAFT'
    check (status in ('DRAFT','POSTED','CANCELLED')),
  notes text,
  created_at timestamptz not null default now(),
  posted_at timestamptz
);

create index if not exists idx_goods_receipts_supplier on public.goods_receipts(supplier_id, received_at desc);
create index if not exists idx_goods_receipts_po on public.goods_receipts(purchase_order_id);

create table if not exists public.goods_receipt_items (
  id uuid primary key default gen_random_uuid(),
  goods_receipt_id uuid not null references public.goods_receipts(id) on delete cascade,
  purchase_order_item_id uuid references public.purchase_order_items(id),
  inventory_item_id uuid not null references public.inventory_items(id),
  purchase_uom_id uuid not null references public.units_of_measure(id),
  purchase_quantity numeric(14,4) not null check (purchase_quantity > 0),
  base_quantity_per_purchase_unit numeric(14,4) not null check (base_quantity_per_purchase_unit > 0),
  base_quantity numeric(14,4) not null check (base_quantity > 0),
  unit_cost_purchase_uom numeric(14,4) not null check (unit_cost_purchase_uom >= 0),
  unit_cost_base numeric(14,6) not null check (unit_cost_base >= 0),
  lot_code text,
  expiration_date date,
  notes text
);

create index if not exists idx_goods_receipt_items_receipt on public.goods_receipt_items(goods_receipt_id);

create table if not exists public.inventory_lots (
  id uuid primary key default gen_random_uuid(),
  inventory_item_id uuid not null references public.inventory_items(id),
  goods_receipt_item_id uuid unique references public.goods_receipt_items(id),
  lot_code text,
  received_at timestamptz not null default now(),
  expiration_date date,
  received_quantity numeric(14,4) not null check (received_quantity >= 0),
  remaining_quantity numeric(14,4) not null check (remaining_quantity >= 0),
  unit_cost_base numeric(14,6) not null default 0 check (unit_cost_base >= 0),
  status text not null default 'AVAILABLE'
    check (status in ('AVAILABLE','DEPLETED','QUARANTINED','DISCARDED')),
  created_at timestamptz not null default now(),
  check (remaining_quantity <= received_quantity)
);

create index if not exists idx_inventory_lots_fefo
  on public.inventory_lots(inventory_item_id, expiration_date, received_at)
  where remaining_quantity > 0 and status = 'AVAILABLE';

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  inventory_item_id uuid not null references public.inventory_items(id),
  inventory_lot_id uuid references public.inventory_lots(id),
  movement_type text not null
    check (movement_type in (
      'PURCHASE_RECEIPT',
      'SALE_CONSUMPTION',
      'WASTE',
      'DAMAGED',
      'EXPIRED',
      'COMPLIMENTARY',
      'STAFF_MEAL',
      'STOCK_COUNT_ADJUSTMENT',
      'MANUAL_IN',
      'MANUAL_OUT',
      'REFUND_RESTOCK',
      'REVERSAL'
    )),
  quantity_delta numeric(14,4) not null check (quantity_delta <> 0),
  unit_cost_base numeric(14,6) not null default 0 check (unit_cost_base >= 0),
  reference_type text,
  reference_id uuid,
  order_id uuid,
  order_item_id uuid,
  reason text,
  recorded_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_stock_movements_item
  on public.stock_movements(inventory_item_id, created_at desc);
create index if not exists idx_stock_movements_order
  on public.stock_movements(order_id, order_item_id);

create table if not exists public.stock_counts (
  id uuid primary key default gen_random_uuid(),
  count_number bigint generated by default as identity unique,
  status text not null default 'DRAFT'
    check (status in ('DRAFT','POSTED','CANCELLED')),
  counted_at timestamptz not null default now(),
  counted_by uuid not null references public.profiles(id),
  posted_by uuid references public.profiles(id),
  posted_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_count_items (
  id uuid primary key default gen_random_uuid(),
  stock_count_id uuid not null references public.stock_counts(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id),
  system_quantity numeric(14,4) not null,
  counted_quantity numeric(14,4) not null check (counted_quantity >= 0),
  variance_quantity numeric(14,4) not null,
  notes text,
  unique (stock_count_id, inventory_item_id)
);

create table if not exists public.supplier_bills (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.suppliers(id),
  goods_receipt_id uuid unique references public.goods_receipts(id),
  supplier_invoice_number text,
  invoice_date date not null default current_date,
  due_date date,
  amount numeric(14,2) not null check (amount >= 0),
  status text not null default 'UNPAID'
    check (status in ('UNPAID','PARTIALLY_PAID','PAID','VOID')),
  notes text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_supplier_bills_supplier on public.supplier_bills(supplier_id, due_date);
create index if not exists idx_supplier_bills_status on public.supplier_bills(status);

create trigger trg_supplier_bills_updated_at
before update on public.supplier_bills
for each row execute function public.set_updated_at();

create table if not exists public.supplier_bill_payments (
  id uuid primary key default gen_random_uuid(),
  supplier_bill_id uuid not null references public.supplier_bills(id),
  payment_method_id uuid not null references public.payment_methods(id),
  amount numeric(14,2) not null check (amount > 0),
  reference_number text,
  paid_at timestamptz not null default now(),
  recorded_by uuid not null references public.profiles(id),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_supplier_bill_payments_bill
  on public.supplier_bill_payments(supplier_bill_id, paid_at);
