-- 0004_finance_invoicing.sql
-- Expenses, invoice sequencing, sales invoices, credit notes and print audit.

create table if not exists public.expense_categories (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  is_active boolean not null default true
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  expense_number bigint generated by default as identity unique,
  expense_date date not null default current_date,
  expense_category_id uuid not null references public.expense_categories(id),
  expense_type text not null default 'OPERATING'
    check (expense_type in ('OPERATING','NON_INVENTORY_PURCHASE','OTHER')),
  description text not null,
  amount numeric(14,2) not null check (amount > 0),
  payment_method_id uuid references public.payment_methods(id),
  supplier_id uuid references public.suppliers(id),
  reference_number text,
  receipt_image_url text,
  status text not null default 'POSTED'
    check (status in ('DRAFT','POSTED','VOIDED')),
  recorded_by uuid not null references public.profiles(id),
  approved_by uuid references public.profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_expenses_date on public.expenses(expense_date desc);
create index if not exists idx_expenses_category on public.expenses(expense_category_id);

create trigger trg_expenses_updated_at
before update on public.expenses
for each row execute function public.set_updated_at();

create table if not exists public.invoice_sequences (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  prefix text not null default '',
  next_number bigint not null default 1 check (next_number > 0),
  number_width smallint not null default 8 check (number_width between 1 and 20),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_invoice_sequences_updated_at
before update on public.invoice_sequences
for each row execute function public.set_updated_at();

create table if not exists public.sales_invoices (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id),
  invoice_sequence_id uuid references public.invoice_sequences(id),
  invoice_number text not null unique,
  status text not null default 'ISSUED'
    check (status in ('ISSUED','VOIDED','CREDITED')),
  issued_at timestamptz not null default now(),

  -- Seller snapshot
  seller_registered_name text,
  seller_trade_name text,
  seller_tin text,
  seller_branch_code text,
  seller_address text,
  seller_tax_registration_status text,

  -- Buyer snapshot, optional for normal walk-in orders
  buyer_name text,
  buyer_address text,
  buyer_tin text,
  buyer_business_style text,

  subtotal numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  vatable_sales numeric(14,2) not null default 0,
  vat_exempt_sales numeric(14,2) not null default 0,
  zero_rated_sales numeric(14,2) not null default 0,
  vat_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,

  issued_by uuid references public.profiles(id) on delete set null,
  device_id uuid references public.devices(id) on delete set null,

  voided_at timestamptz,
  voided_by uuid references public.profiles(id) on delete set null,
  void_reason text,

  created_at timestamptz not null default now()
);

create index if not exists idx_sales_invoices_issued_at
  on public.sales_invoices(issued_at desc);

create table if not exists public.credit_notes (
  id uuid primary key default gen_random_uuid(),
  credit_note_number bigint generated by default as identity unique,
  sales_invoice_id uuid not null references public.sales_invoices(id),
  refund_id uuid unique references public.refunds(id),
  amount numeric(14,2) not null check (amount > 0),
  reason text not null,
  issued_at timestamptz not null default now(),
  issued_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_credit_notes_invoice on public.credit_notes(sales_invoice_id);

create table if not exists public.invoice_print_events (
  id uuid primary key default gen_random_uuid(),
  sales_invoice_id uuid not null references public.sales_invoices(id),
  printed_by uuid references public.profiles(id) on delete set null,
  device_id uuid references public.devices(id) on delete set null,
  printer_name text,
  paper_width_mm smallint check (paper_width_mm in (58,80) or paper_width_mm is null),
  printed_at timestamptz not null default now()
);

create index if not exists idx_invoice_print_events_invoice
  on public.invoice_print_events(sales_invoice_id, printed_at desc);
